# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P1_Ejemplo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 414)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_sumar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sumar.setGeometry(QtCore.QRect(300, 210, 191, 61))
        self.btn_sumar.setStyleSheet("border: 3px solid black;\n"
"background-color: rgb(204, 248, 255);\n"
"border-radius: 8px;")
        self.btn_sumar.setObjectName("btn_sumar")
        self.txt_num1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_num1.setGeometry(QtCore.QRect(210, 100, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.txt_num1.setFont(font)
        self.txt_num1.setStyleSheet("border: 5px solid black;\n"
"border-radius: 8px;")
        self.txt_num1.setText("")
        self.txt_num1.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_num1.setObjectName("txt_num1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(117, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 160, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_num2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_num2.setGeometry(QtCore.QRect(210, 150, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.txt_num2.setFont(font)
        self.txt_num2.setStyleSheet("border: 5px solid black;\n"
"border-radius: 8px;")
        self.txt_num2.setText("")
        self.txt_num2.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_num2.setObjectName("txt_num2")
        self.imagen_3 = QtWidgets.QLabel(self.centralwidget)
        self.imagen_3.setGeometry(QtCore.QRect(500, 280, 111, 71))
        self.imagen_3.setStyleSheet("")
        self.imagen_3.setText("")
        self.imagen_3.setPixmap(QtGui.QPixmap(":/Ejercicios/ImagenGatoEuropeo.png"))
        self.imagen_3.setScaledContents(True)
        self.imagen_3.setObjectName("imagen_3")
        self.imagen = QtWidgets.QLabel(self.centralwidget)
        self.imagen.setGeometry(QtCore.QRect(10, 10, 131, 71))
        self.imagen.setStyleSheet("")
        self.imagen.setText("")
        self.imagen.setPixmap(QtGui.QPixmap(":/Logos/log_uat_nuevo.png"))
        self.imagen.setScaledContents(True)
        self.imagen.setObjectName("imagen")
        self.imagen_2 = QtWidgets.QLabel(self.centralwidget)
        self.imagen_2.setGeometry(QtCore.QRect(540, 0, 91, 71))
        self.imagen_2.setStyleSheet("")
        self.imagen_2.setText("")
        self.imagen_2.setPixmap(QtGui.QPixmap(":/Logos/FIT_logo_vertical.png"))
        self.imagen_2.setScaledContents(True)
        self.imagen_2.setObjectName("imagen_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 625, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_sumar.setText(_translate("MainWindow", "SUMA"))
        self.label.setText(_translate("MainWindow", "Número 1:"))
        self.label_2.setText(_translate("MainWindow", "Número 2:"))
import Recursos_rc
