# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P4_ChecarPuedeVotar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 414)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_comprobar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_comprobar.setGeometry(QtCore.QRect(250, 200, 131, 41))
        self.btn_comprobar.setStyleSheet("border: 3px solid black;\n"
"background-color: rgb(204, 248, 255);\n"
"border-radius: 8px;")
        self.btn_comprobar.setObjectName("btn_comprobar")
        self.txt_edad = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_edad.setGeometry(QtCore.QRect(210, 110, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.txt_edad.setFont(font)
        self.txt_edad.setStyleSheet("border: 5px solid black;\n"
"border-radius: 8px;")
        self.txt_edad.setText("")
        self.txt_edad.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_edad.setObjectName("txt_edad")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(117, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.imagen_3 = QtWidgets.QLabel(self.centralwidget)
        self.imagen_3.setGeometry(QtCore.QRect(500, 280, 111, 71))
        self.imagen_3.setStyleSheet("")
        self.imagen_3.setText("")
        self.imagen_3.setPixmap(QtGui.QPixmap(":/Programas/ImagenGatoEuropeo.png"))
        self.imagen_3.setScaledContents(True)
        self.imagen_3.setObjectName("imagen_3")
        self.imagen = QtWidgets.QLabel(self.centralwidget)
        self.imagen.setGeometry(QtCore.QRect(10, 10, 131, 71))
        self.imagen.setStyleSheet("")
        self.imagen.setText("")
        self.imagen.setPixmap(QtGui.QPixmap(":/Logos/log_uat_nuevo.png"))
        self.imagen.setScaledContents(True)
        self.imagen.setObjectName("imagen")
        self.imagen_2 = QtWidgets.QLabel(self.centralwidget)
        self.imagen_2.setGeometry(QtCore.QRect(520, 0, 101, 81))
        self.imagen_2.setStyleSheet("")
        self.imagen_2.setText("")
        self.imagen_2.setPixmap(QtGui.QPixmap(":/Logos/FIT_logo_vertical.png"))
        self.imagen_2.setScaledContents(True)
        self.imagen_2.setObjectName("imagen_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 625, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_comprobar.setText(_translate("MainWindow", "COMPROBAR"))
        self.label.setText(_translate("MainWindow", "Edad:"))
import Recursos_rc
